<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = [
            [
                'fio' => 'Администратор',
                'email' => 'admin@example.com',
                'password' => Hash::make('admin123'),
                'role' => 'Администратор',
                'group_id' => 1,
                'is_active' => true,
                'first_name' => 'Администратор',
                'last_name' => 'Системы',
                'patronymic' => null,
            ],
            [
                'fio' => 'Иванов Иван Иванович',
                'email' => 'instructor1@example.com',
                'password' => Hash::make('password'),
                'role' => 'Инструктор',
                'group_id' => 1,
                'is_active' => true,
                'first_name' => 'Иван',
                'last_name' => 'Иванов',
                'patronymic' => 'Иванович',
            ],
            [
                'fio' => 'Петров Иван Иванович',
                'email' => 'student1@example.com',
                'password' => Hash::make('password'),
                'role' => 'Обучаемый',
                'group_id' => 1,
                'is_active' => true,
                'first_name' => 'Иван',
                'last_name' => 'Петров',
                'patronymic' => 'Иванович',
            ],
            [
                'fio' => 'Сидоров Иван Иванович',
                'email' => 'student2@example.com',
                'password' => Hash::make('password'),
                'role' => 'Обучаемый',
                'group_id' => 1,
                'is_active' => true,
                'first_name' => 'Иван',
                'last_name' => 'Сидоров',
                'patronymic' => 'Иванович',
            ],
            [
                'fio' => 'Корнеев Иван Иванович',
                'email' => 'student3@example.com',
                'password' => Hash::make('password'),
                'role' => 'Обучаемый',
                'group_id' => 1,
                'is_active' => true,
                'first_name' => 'Иван',
                'last_name' => 'Корнеев',
                'patronymic' => 'Иванович',
            ],
            [
                'fio' => 'Семенов Иван Иванович',
                'email' => 'student4@example.com',
                'password' => Hash::make('password'),
                'role' => 'Обучаемый',
                'group_id' => 1,
                'is_active' => true,
                'first_name' => 'Иван',
                'last_name' => 'Семенов',
                'patronymic' => 'Иванович',
            ],
            [
                'fio' => 'Крупнов Максим Витальевич',
                'email' => 'student5@example.com',
                'password' => Hash::make('password'),
                'role' => 'Обучаемый',
                'group_id' => 1,
                'is_active' => true,
                'first_name' => 'Максим',
                'last_name' => 'Крупнов',
                'patronymic' => 'Витальевич',
            ],
            [
                'fio' => 'Ненадович Иван Иванович',
                'email' => 'student6@example.com',
                'password' => Hash::make('password'),
                'role' => 'Обучаемый',
                'group_id' => 1,
                'is_active' => true,
                'first_name' => 'Иван',
                'last_name' => 'Ненадович',
                'patronymic' => 'Иванович',
            ],
            [
                'fio' => 'Пименов Иван Иванович',
                'email' => 'instructor2@example.com',
                'password' => Hash::make('password'),
                'role' => 'Инструктор',
                'group_id' => 1,
                'is_active' => true,
                'first_name' => 'Иван',
                'last_name' => 'Пименов',
                'patronymic' => 'Иванович',
            ],
            [
                'fio' => 'Пельш Иван Иванович',
                'email' => 'student7@example.com',
                'password' => Hash::make('password'),
                'role' => 'Обучаемый',
                'group_id' => 1,
                'is_active' => true,
                'first_name' => 'Иван',
                'last_name' => 'Пельш',
                'patronymic' => 'Иванович',
            ],
            [
                'fio' => 'Моисеев Иван Иванович',
                'email' => 'student8@example.com',
                'password' => Hash::make('password'),
                'role' => 'Обучаемый',
                'group_id' => 2,
                'is_active' => true,
                'first_name' => 'Иван',
                'last_name' => 'Моисеев',
                'patronymic' => 'Иванович',
            ],
            [
                'fio' => 'Рабинович Хаим Иванович',
                'email' => 'student9@example.com',
                'password' => Hash::make('password'),
                'role' => 'Обучаемый',
                'group_id' => 2,
                'is_active' => true,
                'first_name' => 'Хаим',
                'last_name' => 'Рабинович',
                'patronymic' => 'Иванович',
            ],
            [
                'fio' => 'Медведев Дмитрий Анатольевич',
                'email' => 'student10@example.com',
                'password' => Hash::make('password'),
                'role' => 'Обучаемый',
                'group_id' => 2,
                'is_active' => true,
                'first_name' => 'Дмитрий',
                'last_name' => 'Медведев',
                'patronymic' => 'Анатольевич',
            ],
            [
                'fio' => 'Трунов Иван Семенович',
                'email' => 'student11@example.com',
                'password' => Hash::make('password'),
                'role' => 'Обучаемый',
                'group_id' => 2,
                'is_active' => true,
                'first_name' => 'Иван',
                'last_name' => 'Трунов',
                'patronymic' => 'Семенович',
            ],
            [
                'fio' => 'Селезнев Тимофей Михайлович',
                'email' => 'instructor3@example.com',
                'password' => Hash::make('password'),
                'role' => 'Инструктор',
                'group_id' => 2,
                'is_active' => true,
                'first_name' => 'Тимофей',
                'last_name' => 'Селезнев',
                'patronymic' => 'Михайлович',
            ],
            [
                'fio' => 'Нагиев Дмитрий Владимирович',
                'email' => 'student12@example.com',
                'password' => Hash::make('password'),
                'role' => 'Обучаемый',
                'group_id' => 3,
                'is_active' => true,
                'first_name' => 'Дмитрий',
                'last_name' => 'Нагиев',
                'patronymic' => 'Владимирович',
            ],
            [
                'fio' => 'Шойгу Сергей Кужугетович',
                'email' => 'student13@example.com',
                'password' => Hash::make('password'),
                'role' => 'Обучаемый',
                'group_id' => 3,
                'is_active' => true,
                'first_name' => 'Сергей',
                'last_name' => 'Шойгу',
                'patronymic' => 'Кужугетович',
            ],
            [
                'fio' => 'Великов Вадим Иванович',
                'email' => 'student14@example.com',
                'password' => Hash::make('password'),
                'role' => 'Обучаемый',
                'group_id' => 3,
                'is_active' => true,
                'first_name' => 'Вадим',
                'last_name' => 'Великов',
                'patronymic' => 'Иванович',
            ],
            [
                'fio' => 'Фурсов Андрей Ильич',
                'email' => 'student15@example.com',
                'password' => Hash::make('password'),
                'role' => 'Обучаемый',
                'group_id' => 3,
                'is_active' => true,
                'first_name' => 'Андрей',
                'last_name' => 'Фурсов',
                'patronymic' => 'Ильич',
            ],
            [
                'fio' => 'Савельев Сергей Вячеславович',
                'email' => 'student16@example.com',
                'password' => Hash::make('password'),
                'role' => 'Обучаемый',
                'group_id' => 3,
                'is_active' => true,
                'first_name' => 'Сергей',
                'last_name' => 'Савельев',
                'patronymic' => 'Вячеславович',
            ],
            [
                'fio' => 'Панчин Александр Юрьевич',
                'email' => 'student17@example.com',
                'password' => Hash::make('password'),
                'role' => 'Обучаемый',
                'group_id' => 3,
                'is_active' => true,
                'first_name' => 'Александр',
                'last_name' => 'Панчин',
                'patronymic' => 'Юрьевич',
            ],
        ];

        foreach ($users as $user) {
            User::updateOrCreate(
                ['email' => $user['email']],
                $user
            );
        }
    }
}
